defaults: &defaults
  currencies:
    yen: ¥
    dollar: $
  mail_from: <%= ENV['PIG_BOOK_MAIL_FROM'] %>
  access_token:
    length: 32
    expire_after: <%= 90.days.to_i %>
  new_email_token:
    length: 32
    expire_after: <%= 24.hours.to_i %>
  registration_token:
    length: 32
    expire_after: <%= 24.hours.to_i %>
  password_token:
    length: 32
    expire_after: <%= 24.hours.to_i %>
  tally:
    interval: <%= 5.hours.to_i %>
  breakdown:
    max_count: 20
    name:
      maximum_length: 100
  category:
    max_count: 20
    max_count_of_admin: 99
    name:
      maximum_length: 100
  place:
    max_count: 20
    max_count_of_admin: 99
    name:
      maximum_length: 100
  record:
    max_count: 200
    max_count_of_admin: 9999
    memo:
      maximum_length: 10000
  capture:
    tags:
      maximum_length: 1000
  tag:
    name:
      maximum_length: 20
  user:
    nickname:
      maximum_length: 100
    email:
      maximum_length: 100
    password:
      maximum_length: 72
      minimum_length: 4
  feedback:
    content:
      maximum_length: 10000
    email:
      maximum_length: 100
  notice:
    title:
      maximum_length: 100
    content:
      maximum_length: 10000
  message:
    content:
      maximum_length: 10000
  users:
    per: 20
  feedbacks:
    per: 20
  notices:
    per: 20
  messages:
    per: 20
  records:
    per: 20

development:
  <<: *defaults

test:
  <<: *defaults
  category:
    max_count: 3
    max_count_of_admin: 5
    name:
      maximum_length: 100
  breakdown:
    max_count: 3
    name:
      maximum_length: 100
  place:
    max_count: 3
    max_count_of_admin: 5
    name:
      maximum_length: 100
  record:
    max_count: 3
    max_count_of_admin: 5
    memo:
      maximum_length: 10000
  user:
    nickname:
      maximum_length: 100
    email:
      maximum_length: 100
    password:
      maximum_length: 72
      minimum_length: 4

production:
  <<: *defaults
