default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: account-book-pig_development

test:
  <<: *default
  database: account-book-pig_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: account_book_pig_production
  user: <%= ENV['POSTGRESQL_USERNAME'] %>
  host: <%= ENV['POSTGRESQL_HOST'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
